---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        client: public_dns_clients
        server: public_dns_servers

platforms:
  - name: terraform

suites:
  - name: default
